config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'users#index'
end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :endeavor
end

app/models/endeavor.rb
class Endeavor < ActiveRecord::Base
  belongs_to :user  
  has_many :achievements
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :endeavors
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Endeavor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
</ul>

<%= link_to 'Create New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>
<div id="new-user">
  <%= form_for @user do |f| %>
    <%= f.text_field :email, :placeholder => 'Email' %>
    <%= f.submit 'Create' %>
  <% end %>
</div>

<%= link_to 'Back to All Users', root_path %>